import { createApp } from 'vue'
import { createI18n } from 'vue-i18n'
import { createVuetify } from 'vuetify'
import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'

import App from './App.vue'

const messages = {
  en: {
    appName: 'x10 admin',
    loginTitle: 'Admin login',
    loginSubtitle: 'Sign in to manage profiles, relations, and progression data.',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    profiles: 'Profiles',
    profileWorkspace: 'Profile workspace',
    spheres: 'Spheres',
    game: 'Game',
    gameHint: 'Open placeholder',
    noProfileSelected: 'Select or create a profile to start editing data.',
    createProfile: 'Create profile',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    close: 'Close',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    reload: 'Reload',
    logoutDone: 'Session closed',
    loginFailed: 'Invalid username or password',
    operationFailed: 'Request failed',
    operationDone: 'Saved',
    confirmDelete: 'Delete this item?',
    removeProfile: 'Delete profile',
    profileDetails: 'Profile details',
    fullName: 'Full name',
    birthDate: 'Birth date',
    occupation: 'Occupation',
    telegram: 'Telegram',
    email: 'Email',
    timezone: 'Timezone',
    currentLevel: 'Current level',
    currentBalance: 'Current balance',
    levelsConfigured: 'Configured levels',
    photoUpload: 'Upload photo',
    chooseFile: 'Choose file',
    select: 'Select',
    selected: 'Selected',
    profilePhotos: 'Profile photos',
    tasks: 'Tasks',
    executions: 'Executions',
    balances: 'Balances',
    levels: 'Levels',
    finalizations: 'Finalizations',
    levelState: 'Level state',
    title: 'Title',
    kind: 'Kind',
    cadence: 'Cadence',
    plannedWeight: 'Weight',
    plannedScore: 'Score',
    plannedRate: 'Rate',
    startsOn: 'Starts on',
    status: 'Status',
    positive: 'Positive',
    negative: 'Negative',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    planned: 'Planned',
    archived: 'Archived',
    skipped: 'Skipped',
    execute: 'Execute',
    actualScore: 'Actual score',
    actualRate: 'Actual rate',
    completedAt: 'Completed at',
    code: 'Code',
    ordinal: 'Ordinal',
    minBalance: 'Min balance',
    targetPlannedScore: 'Target score',
    targetPlannedRate: 'Target rate',
    date: 'Date',
    note: 'Note',
    createExecution: 'Create execution',
    createLevel: 'Create level',
    createFinalization: 'Create finalization',
    currentLevelId: 'Current level id',
    lastBalanceId: 'Last balance id',
    updatedAt: 'Updated at',
    profileDeleteHint: 'Deletes profile and nested records.',
    name: 'Name',
    weight: 'Weight',
    createSphere: 'Create sphere',
    gamePlaceholderTitle: 'Game placeholder',
    gamePlaceholderText: 'The future game client will live here. Use the admin panel at the root route for now.',
  },
  ru: {
    appName: 'x10 админка',
    loginTitle: 'Вход администратора',
    loginSubtitle: 'Войдите, чтобы управлять профилями, связями и данными прогрессии.',
    username: 'Логин',
    password: 'Пароль',
    signIn: 'Войти',
    signOut: 'Выйти',
    profiles: 'Профили',
    profileWorkspace: 'Рабочая зона профиля',
    spheres: 'Сферы',
    game: 'Игра',
    gameHint: 'Открыть заглушку',
    noProfileSelected: 'Выберите или создайте профиль, чтобы редактировать данные.',
    createProfile: 'Создать профиль',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    create: 'Создать',
    close: 'Закрыть',
    theme: 'Тема',
    language: 'Язык',
    light: 'Светлая',
    dark: 'Тёмная',
    reload: 'Обновить',
    logoutDone: 'Сессия завершена',
    loginFailed: 'Неверный логин или пароль',
    operationFailed: 'Не удалось выполнить запрос',
    operationDone: 'Сохранено',
    confirmDelete: 'Удалить этот элемент?',
    removeProfile: 'Удалить профиль',
    profileDetails: 'Данные профиля',
    fullName: 'ФИО',
    birthDate: 'Дата рождения',
    occupation: 'Роль / занятие',
    telegram: 'Telegram',
    email: 'Email',
    timezone: 'Часовой пояс',
    currentLevel: 'Текущий уровень',
    currentBalance: 'Текущий баланс',
    levelsConfigured: 'Настроено уровней',
    photoUpload: 'Загрузить фото',
    chooseFile: 'Выбрать файл',
    select: 'Выбрать',
    selected: 'Выбрано',
    profilePhotos: 'Фотографии профиля',
    tasks: 'Задачи',
    executions: 'Выполнения',
    balances: 'Балансы',
    levels: 'Уровни',
    finalizations: 'Финализации',
    levelState: 'Состояние уровня',
    title: 'Название',
    kind: 'Тип',
    cadence: 'Периодичность',
    plannedWeight: 'Вес',
    plannedScore: 'Оценка',
    plannedRate: 'Процент',
    startsOn: 'Дата старта',
    status: 'Статус',
    positive: 'Позитивная',
    negative: 'Негативная',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    year: 'Год',
    planned: 'Запланирована',
    archived: 'Архив',
    skipped: 'Пропущена',
    execute: 'Выполнить',
    actualScore: 'Факт. оценка',
    actualRate: 'Факт. процент',
    completedAt: 'Выполнено в',
    code: 'Код',
    ordinal: 'Порядок',
    minBalance: 'Мин. баланс',
    targetPlannedScore: 'Целевая оценка',
    targetPlannedRate: 'Целевой процент',
    date: 'Дата',
    note: 'Заметка',
    createExecution: 'Создать выполнение',
    createLevel: 'Создать уровень',
    createFinalization: 'Создать финализацию',
    currentLevelId: 'ID текущего уровня',
    lastBalanceId: 'ID последнего баланса',
    updatedAt: 'Обновлено',
    profileDeleteHint: 'Удаляет профиль и все вложенные записи.',
    name: 'Название',
    weight: 'Вес',
    createSphere: 'Создать сферу',
    gamePlaceholderTitle: 'Заглушка игры',
    gamePlaceholderText: 'Будущий игровой клиент появится здесь. Пока используйте админку на корневом маршруте.',
  },
}

const storedTheme = localStorage.getItem('x10.theme')
const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
const browserLocale = (navigator.language || 'en').toLowerCase()
const locale =
  localStorage.getItem('x10.language') || (browserLocale.startsWith('ru') ? 'ru' : 'en')

const i18n = createI18n({
  legacy: false,
  locale,
  fallbackLocale: 'en',
  messages,
})

const vuetify = createVuetify({
  theme: {
    defaultTheme: storedTheme || (prefersDark ? 'dark' : 'light'),
  },
})

createApp(App).use(i18n).use(vuetify).mount('#app')
